### ISSUE TITLE
Missing explicit license

### ISSUE THREAD

**Issue by Geolykt** [thetealviper/Spigot_FarmCraft#3]
There is currently no explicit license, which especially on Github can be problematic and even more so thanks to bukkit's license which makes matters even more complicated, I recommend you to set the license explicitly as otherwise potential contributors may not know what they can do with the application and source.

**Comment by thetealviper** [comment]
That is a very valid and fair point, however I prefer to work on an intimate, directly interpersonal level. People ask, I give or refuse my consent (so far 100% have been given), and either we as individuals trust each other or we don't. In the world of legalities I am well aware that does not cut it and having a gray area is sacrilegious to many, but I prefer to maintain a tad bit of humanity in my interactions haha.
