### ISSUE TITLE
Seeds drop in worldguard/claimed region

### ISSUE THREAD

**Issue by 1Nugget2Poulet** [thetealviper/Spigot_FarmCraft#5]
Ayo
there a bug with claimed region from worldguard and griefprevention where you can break infinite grass and get seeds from them (i saw you already tried to fix it but didn't work)

That pretty much all

**Comment by thetealviper** [comment]
Interesting. Not sure how the issue came back but it should be fixed now via [1.20.4.a.2] 👍 Thanks for report.
